name: Pull request

on:
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  build:
    uses: ./.github/workflows/build.yml

  pull-request:
    name: Pull request success
    needs: build
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - run: "true"
